/**
 * Rehbar — Accumn GST Analytical Report Extraction
 * Returns 200 immediately; processes via EdgeRuntime.waitUntil (no HTTP timeout).
 * Client polls financial_documents.extraction_status for completion.
 */

import { createClient, SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2.45.4";
import { callAI, type FileContent } from "../_shared/ai-caller.ts";

declare const Deno: { env: { get(k: string): string | undefined } };
declare const EdgeRuntime: { waitUntil(p: Promise<unknown>): void };

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};
const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { ...CORS, "content-type": "application/json" } });

// ── Background extraction ─────────────────────────────────────────────────────

async function runExtraction(
  case_id: string,
  document_id: string,
  user_id: string,
  file_path: string,
  admin: SupabaseClient,
): Promise<void> {
  try {
    const MISTRAL_KEY = Deno.env.get("MISTRAL_API_KEY");
    if (!MISTRAL_KEY) throw new Error("MISTRAL_API_KEY secret not set");

    // Signed URL — Mistral downloads the PDF directly (no base64 overhead)
    const { data: signed } = await admin.storage.from("case-files").createSignedUrl(file_path, 600);
    if (!signed?.signedUrl) throw new Error("Could not create signed URL for PDF");

    // Step 1: OCR (no AbortSignal — background task can take as long as needed)
    const ocrRes = await fetch("https://api.mistral.ai/v1/ocr", {
      method: "POST",
      headers: { "Authorization": `Bearer ${MISTRAL_KEY}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        model:    "mistral-ocr-latest",
        document: { type: "document_url", document_url: signed.signedUrl },
      }),
    });
    if (!ocrRes.ok) {
      const err = await ocrRes.text();
      throw new Error(`Mistral OCR ${ocrRes.status}: ${err.slice(0, 300)}`);
    }
    const ocrJson = await ocrRes.json();
    const ocrText = ((ocrJson.pages ?? []) as { markdown?: string }[])
      .map((p: { markdown?: string }) => p.markdown ?? "").join("\n\n").slice(0, 120_000);
    if (!ocrText.trim()) throw new Error("Mistral OCR returned empty text");

    // Step 2: Structured extraction from the OCR text
    const files: FileContent[] = [{ type: "text", text: ocrText }];

    const args = await callAI({
      systemPrompt: `You are an expert at parsing Accumn GST Advisory Reports — structured analytical reports generated by the Accumn platform for Indian businesses. These reports contain multiple labelled sections: Flags/Alerts, Company Profile, Sales Summary by FY, Customer/Supplier Concentration tables, Geography breakup (state-wise), B2B Analysis, Product/HSN concentration, Tax Details, and GSTR-1 vs GSTR-3B vs GSTR-9 comparison.

DETECTION: Set is_accumn=true only if the document is clearly an Accumn-style GST analytical report (looks like a multi-section PDF with flags, concentration tables, and FY-wise summaries). Raw GSTR return XMLs, bank statements, P&L statements → is_accumn=false.

EXTRACTION RULES:
- Monetary amounts: extract as the document's native unit (usually INR Lakhs). Do NOT convert.
- Percentages: store as decimal NUMBER (e.g., 15.3% → 15.3, NOT 0.153).
- Omit fields you cannot confidently read — never invent data.
- For concentration tables: capture ALL rows visible (up to top 10 per period).
- For geography: capture all states listed.
- For GSTR comparison: capture per-period rows.`,
      userText: "Extract all sections from this document. Detect if it is an Accumn GST analytical report.",
      files,
      toolName: "submit_accumn_report",
      toolDescription: "Submit the extracted Accumn GST analytical report data.",
      toolSchema: {
        is_accumn: { type: "boolean", description: "True only if this is an Accumn-format GST analytical report" },
        flags: {
          type: "array",
          description: "Risk flags/alerts listed in the report",
          items: {
            type: "object",
            properties: {
              flag_name:   { type: "string" },
              severity:    { type: "string", enum: ["HIGH", "MEDIUM", "LOW"] },
              description: { type: "string" },
            },
            required: ["flag_name", "severity", "description"],
            additionalProperties: false,
          },
        },
        company_profile: {
          type: "object",
          properties: {
            name:              { type: "string" },
            gstin:             { type: "string" },
            pan:               { type: "string" },
            constitution:      { type: "string" },
            state:             { type: "string" },
            business_type:     { type: "string" },
            registration_date: { type: "string" },
            report_date:       { type: "string" },
          },
          additionalProperties: false,
        },
        sales_summary: {
          type: "array",
          items: {
            type: "object",
            properties: {
              period:           { type: "string" },
              adjusted_revenue: { type: ["number", "null"] },
              net_revenue:      { type: ["number", "null"] },
              sales_return_pct: { type: ["number", "null"] },
              advance_pct:      { type: ["number", "null"] },
              gross_margin_pct: { type: ["number", "null"] },
              ebitda_pct:       { type: ["number", "null"] },
              pat_pct:          { type: ["number", "null"] },
            },
            required: ["period"],
            additionalProperties: false,
          },
        },
        customer_categories: {
          type: "array",
          items: {
            type: "object",
            properties: {
              period:    { type: "string" },
              b2b:       { type: ["number", "null"] },
              b2c_small: { type: ["number", "null"] },
              b2c_large: { type: ["number", "null"] },
              export:    { type: ["number", "null"] },
              nil_rated: { type: ["number", "null"] },
              total:     { type: ["number", "null"] },
            },
            required: ["period"],
            additionalProperties: false,
          },
        },
        geography: {
          type: "array",
          items: {
            type: "object",
            properties: {
              period: { type: "string" },
              state:  { type: "string" },
              amount: { type: "number" },
              pct:    { type: "number" },
            },
            required: ["period", "state", "amount", "pct"],
            additionalProperties: false,
          },
        },
        customer_concentration: {
          type: "array",
          items: {
            type: "object",
            properties: {
              period: { type: "string" },
              rank:   { type: "number" },
              name:   { type: "string" },
              gstin:  { type: "string" },
              amount: { type: "number" },
              pct:    { type: "number" },
            },
            required: ["period", "rank", "name", "amount", "pct"],
            additionalProperties: false,
          },
        },
        supplier_concentration: {
          type: "array",
          items: {
            type: "object",
            properties: {
              period: { type: "string" },
              rank:   { type: "number" },
              name:   { type: "string" },
              gstin:  { type: "string" },
              amount: { type: "number" },
              pct:    { type: "number" },
            },
            required: ["period", "rank", "name", "amount", "pct"],
            additionalProperties: false,
          },
        },
        product_concentration: {
          type: "array",
          items: {
            type: "object",
            properties: {
              period:      { type: "string" },
              chapter:     { type: "string" },
              hsn:         { type: "string" },
              description: { type: "string" },
              amount:      { type: "number" },
              pct:         { type: "number" },
            },
            required: ["period", "description", "amount", "pct"],
            additionalProperties: false,
          },
        },
        tax_details: {
          type: "array",
          items: {
            type: "object",
            properties: {
              period:        { type: "string" },
              wc_investment: { type: ["number", "null"] },
              output_tax:    { type: ["number", "null"] },
              igst:          { type: ["number", "null"] },
              cgst:          { type: ["number", "null"] },
              sgst:          { type: ["number", "null"] },
              itc_availed:   { type: ["number", "null"] },
              net_tax:       { type: ["number", "null"] },
            },
            required: ["period"],
            additionalProperties: false,
          },
        },
        gstr_comparison: {
          type: "array",
          items: {
            type: "object",
            properties: {
              period:          { type: "string" },
              gstr1_turnover:  { type: ["number", "null"] },
              gstr3b_turnover: { type: ["number", "null"] },
              gstr9_turnover:  { type: ["number", "null"] },
              gstr1_tax:       { type: ["number", "null"] },
              gstr3b_tax:      { type: ["number", "null"] },
              difference:      { type: ["number", "null"] },
            },
            required: ["period"],
            additionalProperties: false,
          },
        },
        circular_transactions: {
          type: "array",
          items: {
            type: "object",
            properties: {
              entity:          { type: "string" },
              gstin:           { type: "string" },
              sale_amount:     { type: ["number", "null"] },
              purchase_amount: { type: ["number", "null"] },
              note:            { type: "string" },
            },
            required: ["entity"],
            additionalProperties: false,
          },
        },
      },
      toolRequired: ["is_accumn"],
      maxTokens: 8192,
      retries: 1,
      timeoutMs: 90_000,
    });

    if (!args.is_accumn) {
      // Not Accumn — mark as extracted but flag it
      await admin.from("financial_documents")
        .update({ extraction_status: "extracted", extraction_error: "NOT_ACCUMN" })
        .eq("id", document_id);
      return;
    }

    // Upsert report data
    const { error: upsertErr } = await (admin as unknown as {
      from: (t: string) => { upsert: (d: unknown, o: unknown) => Promise<{ error: unknown }> }
    }).from("gst_accumn_reports").upsert({
      case_id, document_id, user_id,
      report_data: args,
      updated_at: new Date().toISOString(),
    }, { onConflict: "case_id" });
    if (upsertErr) throw new Error(String((upsertErr as { message?: string }).message ?? upsertErr));

    await admin.from("financial_documents")
      .update({ extraction_status: "extracted", extraction_error: null })
      .eq("id", document_id);

  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    console.error("extract-gst-accumn background error:", msg);
    await admin.from("financial_documents")
      .update({ extraction_status: "failed", extraction_error: msg.slice(0, 500) })
      .eq("id", document_id);
  }
}

// ── HTTP handler ──────────────────────────────────────────────────────────────

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: CORS });

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) return json({ error: "Unauthorized" }, 401);

    const body = await req.json() as { case_id: string; document_id: string };
    const { case_id, document_id } = body;
    if (!case_id || !document_id) return json({ error: "Missing fields" }, 400);

    const admin = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
    const userClient = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } },
    );
    const { data: { user } } = await userClient.auth.getUser();
    if (!user) return json({ error: "Unauthorized" }, 401);

    const { data: doc } = await admin.from("financial_documents").select("*").eq("id", document_id).single();
    if (!doc) return json({ error: "Document not found" }, 404);

    if (doc.file_type !== "pdf") return json({ ok: true, is_accumn: false });

    // Mark running, then return immediately — background job does the work
    await admin.from("financial_documents")
      .update({ extraction_status: "running", extraction_error: null })
      .eq("id", document_id);

    EdgeRuntime.waitUntil(
      runExtraction(case_id, document_id, user.id, doc.file_path, admin)
    );

    return json({ ok: true, processing: true });

  } catch (e) {
    console.error("extract-gst-accumn:", e);
    return json({ error: String(e) }, 500);
  }
});
