/**
 * Rehbar — Accumn GST Analytical Report Extraction
 * Detects and extracts all sections from Accumn-format GST advisory reports.
 * Stores structured JSON in gst_accumn_reports table (one per case, upsert).
 */

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.4";
import { callAI, type FileContent } from "../_shared/ai-caller.ts";

declare const Deno: { env: { get(k: string): string | undefined } };

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { ...CORS, "content-type": "application/json" } });

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: CORS });

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) return json({ error: "Unauthorized" }, 401);

    const body = await req.json() as { case_id: string; document_id: string; pdf_text?: string };
    const { case_id, document_id, pdf_text } = body;
    if (!case_id || !document_id) return json({ error: "Missing fields" }, 400);

    const admin = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
    const userClient = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } },
    );
    const { data: { user } } = await userClient.auth.getUser();
    if (!user) return json({ error: "Unauthorized" }, 401);

    const { data: doc } = await admin.from("financial_documents").select("*").eq("id", document_id).single();
    if (!doc) return json({ error: "Document not found" }, 404);

    // Only process PDFs
    if (doc.file_type !== "pdf") return json({ ok: true, is_accumn: false });

    // Build file content: prefer client-supplied text (faster, more reliable) over PDF vision
    let files: FileContent[];
    if (pdf_text && pdf_text.length > 200) {
      // Cap at ~60 000 chars — Accumn reports are structured; the key data is in the first portion
      files = [{ type: "text", text: pdf_text.slice(0, 60_000) }];
    } else {
      // Fallback: download PDF from storage and pass as vision
      const { data: file } = await admin.storage.from("case-files").download(doc.file_path);
      if (!file) throw new Error("File download failed");
      const bytes = new Uint8Array(await file.arrayBuffer());
      let b64 = ""; const cs = 0x8000;
      for (let i = 0; i < bytes.length; i += cs)
        b64 += String.fromCharCode.apply(null, Array.from(bytes.subarray(i, i + cs)));
      files = [{ type: "pdf", base64: btoa(b64) }];
    }

    const args = await callAI({
      systemPrompt: `You are an expert at parsing Accumn GST Advisory Reports — structured analytical reports generated by the Accumn platform for Indian businesses. These reports contain multiple labelled sections: Flags/Alerts, Company Profile, Sales Summary by FY, Customer/Supplier Concentration tables, Geography breakup (state-wise), B2B Analysis, Product/HSN concentration, Tax Details, and GSTR-1 vs GSTR-3B vs GSTR-9 comparison.

DETECTION: Set is_accumn=true only if the document is clearly an Accumn-style GST analytical report (looks like a multi-section PDF with flags, concentration tables, and FY-wise summaries). Raw GSTR return XMLs, bank statements, P&L statements → is_accumn=false.

EXTRACTION RULES:
- Monetary amounts: extract as the document's native unit (usually INR Lakhs). Do NOT convert.
- Percentages: store as decimal NUMBER (e.g., 15.3% → 15.3, NOT 0.153).
- Omit fields you cannot confidently read — never invent data.
- For concentration tables: capture ALL rows visible (up to top 10 per period).
- For geography: capture all states listed.
- For GSTR comparison: capture per-period rows.`,
      userText: "Extract all sections from this document. Detect if it is an Accumn GST analytical report.",
      files,
      toolName: "submit_accumn_report",
      toolDescription: "Submit the extracted Accumn GST analytical report data.",
      toolSchema: {
        is_accumn: { type: "boolean", description: "True only if this is an Accumn-format GST analytical report" },
        flags: {
          type: "array",
          description: "Risk flags/alerts listed in the report",
          items: {
            type: "object",
            properties: {
              flag_name:   { type: "string" },
              severity:    { type: "string", enum: ["HIGH", "MEDIUM", "LOW"] },
              description: { type: "string" },
            },
            required: ["flag_name", "severity", "description"],
            additionalProperties: false,
          },
        },
        company_profile: {
          type: "object",
          description: "Company and GSTIN details from the report header",
          properties: {
            name:              { type: "string" },
            gstin:             { type: "string" },
            pan:               { type: "string" },
            constitution:      { type: "string" },
            state:             { type: "string" },
            business_type:     { type: "string" },
            registration_date: { type: "string" },
            report_date:       { type: "string" },
          },
          additionalProperties: false,
        },
        sales_summary: {
          type: "array",
          description: "FY-wise sales summary (FY 2021-22, FY 2022-23, FY 2023-24, TTM etc.)",
          items: {
            type: "object",
            properties: {
              period:            { type: "string" },
              adjusted_revenue:  { type: ["number", "null"] },
              net_revenue:       { type: ["number", "null"] },
              sales_return_pct:  { type: ["number", "null"] },
              advance_pct:       { type: ["number", "null"] },
              gross_margin_pct:  { type: ["number", "null"] },
              ebitda_pct:        { type: ["number", "null"] },
              pat_pct:           { type: ["number", "null"] },
            },
            required: ["period"],
            additionalProperties: false,
          },
        },
        customer_categories: {
          type: "array",
          description: "B2B/B2C/Export category breakup by period",
          items: {
            type: "object",
            properties: {
              period:    { type: "string" },
              b2b:       { type: ["number", "null"] },
              b2c_small: { type: ["number", "null"] },
              b2c_large: { type: ["number", "null"] },
              export:    { type: ["number", "null"] },
              nil_rated: { type: ["number", "null"] },
              total:     { type: ["number", "null"] },
            },
            required: ["period"],
            additionalProperties: false,
          },
        },
        geography: {
          type: "array",
          description: "State-wise sales breakup (all states, all periods)",
          items: {
            type: "object",
            properties: {
              period: { type: "string" },
              state:  { type: "string" },
              amount: { type: "number" },
              pct:    { type: "number" },
            },
            required: ["period", "state", "amount", "pct"],
            additionalProperties: false,
          },
        },
        customer_concentration: {
          type: "array",
          description: "Top customers by period (all FYs)",
          items: {
            type: "object",
            properties: {
              period: { type: "string" },
              rank:   { type: "number" },
              name:   { type: "string" },
              gstin:  { type: "string" },
              amount: { type: "number" },
              pct:    { type: "number" },
            },
            required: ["period", "rank", "name", "amount", "pct"],
            additionalProperties: false,
          },
        },
        supplier_concentration: {
          type: "array",
          description: "Top suppliers/vendors by period (all FYs)",
          items: {
            type: "object",
            properties: {
              period: { type: "string" },
              rank:   { type: "number" },
              name:   { type: "string" },
              gstin:  { type: "string" },
              amount: { type: "number" },
              pct:    { type: "number" },
            },
            required: ["period", "rank", "name", "amount", "pct"],
            additionalProperties: false,
          },
        },
        product_concentration: {
          type: "array",
          description: "Product/HSN-wise sales by period",
          items: {
            type: "object",
            properties: {
              period:      { type: "string" },
              chapter:     { type: "string" },
              hsn:         { type: "string" },
              description: { type: "string" },
              amount:      { type: "number" },
              pct:         { type: "number" },
            },
            required: ["period", "description", "amount", "pct"],
            additionalProperties: false,
          },
        },
        tax_details: {
          type: "array",
          description: "Tax payment and ITC details by period",
          items: {
            type: "object",
            properties: {
              period:        { type: "string" },
              wc_investment: { type: ["number", "null"] },
              output_tax:    { type: ["number", "null"] },
              igst:          { type: ["number", "null"] },
              cgst:          { type: ["number", "null"] },
              sgst:          { type: ["number", "null"] },
              itc_availed:   { type: ["number", "null"] },
              net_tax:       { type: ["number", "null"] },
            },
            required: ["period"],
            additionalProperties: false,
          },
        },
        gstr_comparison: {
          type: "array",
          description: "GSTR-1 vs GSTR-3B vs GSTR-9 reconciliation by period",
          items: {
            type: "object",
            properties: {
              period:           { type: "string" },
              gstr1_turnover:   { type: ["number", "null"] },
              gstr3b_turnover:  { type: ["number", "null"] },
              gstr9_turnover:   { type: ["number", "null"] },
              gstr1_tax:        { type: ["number", "null"] },
              gstr3b_tax:       { type: ["number", "null"] },
              difference:       { type: ["number", "null"] },
            },
            required: ["period"],
            additionalProperties: false,
          },
        },
        circular_transactions: {
          type: "array",
          description: "Entities flagged for potential circular transactions",
          items: {
            type: "object",
            properties: {
              entity:           { type: "string" },
              gstin:            { type: "string" },
              sale_amount:      { type: ["number", "null"] },
              purchase_amount:  { type: ["number", "null"] },
              note:             { type: "string" },
            },
            required: ["entity"],
            additionalProperties: false,
          },
        },
      },
      toolRequired: ["is_accumn"],
      maxTokens: 16000,
      retries: 0,
      timeoutMs: 130_000,
    });

    if (!args.is_accumn) {
      return json({ ok: true, is_accumn: false });
    }

    // Upsert — one record per case, latest extraction wins
    const { error: upsertErr } = await (admin as unknown as { from: (t: string) => { upsert: (d: unknown, o: unknown) => Promise<{ error: unknown }> } })
      .from("gst_accumn_reports")
      .upsert({
        case_id,
        document_id,
        user_id: user.id,
        report_data: args,
        updated_at: new Date().toISOString(),
      }, { onConflict: "case_id" });

    if (upsertErr) throw new Error(String((upsertErr as { message?: string }).message ?? upsertErr));

    return json({ ok: true, is_accumn: true });

  } catch (e) {
    console.error("extract-gst-accumn:", e);
    return json({ error: String(e) }, 500);
  }
});
